language: php
php:
 - 7.2
 - 7.3
env: DB=mysql
services:
- mysql
before_script:
- npm install -g bower
- composer install
script: phpunit --configuration core/phpunit.xml
before_install:
- mysql -e 'CREATE DATABASE tipi_proto;'